require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FileDownloadRulesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FileDownloadRule. As you add validations to FileDownloadRule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FileDownloadRulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all file_download_rules as @file_download_rules" do
      file_download_rule = FileDownloadRule.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:file_download_rules)).to eq([file_download_rule])
    end
  end

  describe "GET #show" do
    it "assigns the requested file_download_rule as @file_download_rule" do
      file_download_rule = FileDownloadRule.create! valid_attributes
      get :show, {:id => file_download_rule.to_param}, valid_session
      expect(assigns(:file_download_rule)).to eq(file_download_rule)
    end
  end

  describe "GET #new" do
    it "assigns a new file_download_rule as @file_download_rule" do
      get :new, {}, valid_session
      expect(assigns(:file_download_rule)).to be_a_new(FileDownloadRule)
    end
  end

  describe "GET #edit" do
    it "assigns the requested file_download_rule as @file_download_rule" do
      file_download_rule = FileDownloadRule.create! valid_attributes
      get :edit, {:id => file_download_rule.to_param}, valid_session
      expect(assigns(:file_download_rule)).to eq(file_download_rule)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FileDownloadRule" do
        expect {
          post :create, {:file_download_rule => valid_attributes}, valid_session
        }.to change(FileDownloadRule, :count).by(1)
      end

      it "assigns a newly created file_download_rule as @file_download_rule" do
        post :create, {:file_download_rule => valid_attributes}, valid_session
        expect(assigns(:file_download_rule)).to be_a(FileDownloadRule)
        expect(assigns(:file_download_rule)).to be_persisted
      end

      it "redirects to the created file_download_rule" do
        post :create, {:file_download_rule => valid_attributes}, valid_session
        expect(response).to redirect_to(FileDownloadRule.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved file_download_rule as @file_download_rule" do
        post :create, {:file_download_rule => invalid_attributes}, valid_session
        expect(assigns(:file_download_rule)).to be_a_new(FileDownloadRule)
      end

      it "re-renders the 'new' template" do
        post :create, {:file_download_rule => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested file_download_rule" do
        file_download_rule = FileDownloadRule.create! valid_attributes
        put :update, {:id => file_download_rule.to_param, :file_download_rule => new_attributes}, valid_session
        file_download_rule.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested file_download_rule as @file_download_rule" do
        file_download_rule = FileDownloadRule.create! valid_attributes
        put :update, {:id => file_download_rule.to_param, :file_download_rule => valid_attributes}, valid_session
        expect(assigns(:file_download_rule)).to eq(file_download_rule)
      end

      it "redirects to the file_download_rule" do
        file_download_rule = FileDownloadRule.create! valid_attributes
        put :update, {:id => file_download_rule.to_param, :file_download_rule => valid_attributes}, valid_session
        expect(response).to redirect_to(file_download_rule)
      end
    end

    context "with invalid params" do
      it "assigns the file_download_rule as @file_download_rule" do
        file_download_rule = FileDownloadRule.create! valid_attributes
        put :update, {:id => file_download_rule.to_param, :file_download_rule => invalid_attributes}, valid_session
        expect(assigns(:file_download_rule)).to eq(file_download_rule)
      end

      it "re-renders the 'edit' template" do
        file_download_rule = FileDownloadRule.create! valid_attributes
        put :update, {:id => file_download_rule.to_param, :file_download_rule => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested file_download_rule" do
      file_download_rule = FileDownloadRule.create! valid_attributes
      expect {
        delete :destroy, {:id => file_download_rule.to_param}, valid_session
      }.to change(FileDownloadRule, :count).by(-1)
    end

    it "redirects to the file_download_rules list" do
      file_download_rule = FileDownloadRule.create! valid_attributes
      delete :destroy, {:id => file_download_rule.to_param}, valid_session
      expect(response).to redirect_to(file_download_rules_url)
    end
  end

end
